{"name": "test_login_fail_form_error[data1]", "status": "passed", "attachments": [{"name": "log", "source": "a0075546-34ef-4d38-930c-73f509b0f9ee-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720', 'password': 'python', 'check': '请输入正确的手机号'}"}], "start": 1567138257221, "stop": 1567138257838, "uuid": "b1177157-df54-45ae-8d21-b8568393f717", "historyId": "865e1be972973c7d7b834c2f11a00912", "testCaseId": "d9574c1722641d515e9f2f722dc354c5", "fullName": "testcases.test_login6.Test_Login#test_login_fail_form_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login6"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "liliangdeMacBook-Pro.local"}, {"name": "thread", "value": "68435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login6"}]}